name: urfu_navigator_mobile
description: "The flutter project for urfu_navigator"
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  reorderables: ^0.6.0
  yandex_mapkit: ^4.1.0
  equatable: ^2.0.0
  provider: ^6.1.2
  http: ^1.2.2
  flutter_svg: ^2.0.14
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/img/urfu-bodies-img/
    - assets/img/points/
    - assets/img/favicon/
    - assets/img/socials/
