name: urfu_navigator_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  reorderables: ^0.6.0
  yandex_mapkit: ^4.1.0
  equatable: ^2.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/urfu-bodies-img/
    - assets/img/points/
    - assets/img/favicon/
