name: urfu_navigator_mobile
description: "The flutter project for urfu_navigator"
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  reorderables: ^0.6.0
  yandex_mapkit: ^4.1.0
  equatable: ^2.0.0
  provider: ^6.1.2
  http: ^1.2.2
  flutter_animate: ^4.5.0
  svg_path_parser: ^1.1.2
  dartz: ^0.10.1
  shared_preferences: ^2.3.3
  internet_connection_checker: ^1.0.0+1
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  flutter_svg: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  freezed: ^2.5.7

flutter:
  uses-material-design: true
  assets:
    - assets/img/urfu-bodies-img/
    - assets/img/points/
    - assets/img/favicon/
    - assets/img/socials/
