name: "Build & Release Dev"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Bump Version
        id: bump_version
        run: |
          current_version=$(grep '^version:' pubspec.yaml | awk '{print $2}' | tr -d '\r')
          IFS='.' read -r major minor patch <<< "${current_version%-*}"
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"
          echo "New version: $new_version"
          sed -i "s/^version: .*/version: $new_version/" pubspec.yaml
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Commit Changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add pubspec.yaml
          git commit -m "Bump version to ${{ env.NEW_VERSION }}"
          git push

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Create env file with MAPKIT_API_KEY
        run: |
          mkdir -p android/app/src/main/assets
          echo "MAPKIT_API_KEY=${{ secrets.MAPKIT_API_KEY }}" > android/app/src/main/assets/env

      - name: Build APK and ABB
        run: |
          export MAPKIT_API_KEY=${{ secrets.MAPKIT_API_KEY }}
          flutter build apk --verbose
          flutter build appbundle --verbose

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab"
          tag: v${{ env.NEW_VERSION }}
          token: ${{ secrets.TOKEN }}